on: [push, pull_request]

jobs:
  eslint:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Node v18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run ESLint
        run: yarn lint

  typescript:
    name: TypeScript Transpile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Node v18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install --immutable

      - name: TypeScript Test
        run: yarn types:check